### PR TITLE
integrate a codesandbox

### PR DESCRIPTION
**Pull request by kailoon**
1. Adding CSB config file but I am not sure how to do as you wanted.
2. Next, Astro and Remix homepages are changed.

### CODE REVIEW

**Comment by kaminskypavel** [comment]
@kailoon , i'm opening CSB on your fork ([link](https://codesandbox.io/s/github/kailoon/fullpower-stack)) but it doesnt seem to work, are you sure `sandbox.config.json` should be empty?

**Comment by kaminskypavel** [comment]
is there a config to make the tab open vertically instead of horizontally, also looking on these configs it looks like we'd better set node to be 18

```
{
  "template": "node",
  "infiniteLoopProtection": true,
  "hardReloadOnChange": false,
  "view": "browser",
  "container": {
    "node": "16"
  }
}
```

**Comment by kailoon** [comment]
> edit : actually this [links works](https://codesandbox.io/p/github/kailoon/fullpower-stack)! im not sure what is the difference between `https://codesandbox.io/p` and `https://codesandbox.io/s`
> 
> @kailoon , i'm opening CSB on your fork ([link](https://codesandbox.io/s/github/kailoon/fullpower-stack)) but it doesnt seem to work, are you sure `sandbox.config.json` should be empty?

With `p` - Explore any open source repository through CodeSandbox Eg: https://envato.d.pr/i/gG0SnS
With `s` - is a normal CSB editor

https://codesandbox.io/docs/learn/getting-started/open-source
This is new to me as well, I hope I understand it correctly :p

> is there a config to make the tab open vertically instead of horizontally, also looking on these configs it looks like we'd better set node to be 18

Not sure if that's possible but these are the available options https://codesandbox.io/docs/learn/sandboxes/configuration#sandbox-configuration

**Comment by kaminskypavel** [comment]
got it. merging and closing.
thanks for the explanation @kailoon!

**Comment by kaminskypavel** [comment]
@kailoon what am I missing? 
I was under the impression the following link will reflect #master in CSB ?

https://codesandbox.io/p/github/kaminskypavel/fullpower-stack/master?file=%2Fsandbox.config.json

**Comment by kailoon** [comment]
It is https://envato.d.pr/i/rsF5Gx no?

**Comment by kaminskypavel** [comment]
weird but now the link is working 🤷.

anyways feel free to "beautify" the main pages of astro/remix etc..

**Pull request merged**
