### PR TITLE
Optimization/ change order of providers

### PR DESCRIPTION
**Pull request by vithano**
based on example from tanstack
https://tanstack.com/router/v1/docs/examples/react/with-trpc-react-query?file=client%2Fmain.tsx

### CODE REVIEW

**Comment by kaminskypavel** [comment]
@vithano since there are no deps between the providers why do we need this exact order?

**Comment by kaminskypavel** [comment]
btw, thanks for the contribution with other PRs.

mind creating a cool dynamic CONTRIBUTION sections in md?

**Comment by vithano** [comment]
youre correct, im new to most of the technologies you use here so i was under the impression the state management provider changes all the underlying elements every time its state changes, ran some tests apparently it doesn't , did check with the official docs and this is the structure they use, i did notice there's a problem with TanStackRouterDevtools , they run a re-render every 250ms and it causes a lot of flicker on the screen when trying to test performance, i know they are still in beta, you want to use them instead of react router or just playing around?

**Comment by vithano** [comment]
also added action to add contributors 🙌

**Pull request closed without merging**
